# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CQW1jiX7BdBPOMKsp4FjAKAIKNB-wr--
"""

import numpy as np
import pandas as pd
from sklearn import tree

breastCancer = pd.read_csv('Breast_cancer.csv')

breastCancer.head()

print(breastCancer)

breastCancer = breastCancer.to_numpy()

print(breastCancer)

dataTrain = np.concatenate((breastCancer[0:200, :], breastCancer[300:500, :]),
                           axis=0)
dataTest = np.concatenate((breastCancer[200:300, :], breastCancer[500:569, :]),
                          axis=0)

print(dataTrain)
len(dataTrain)

print(dataTest)
len(dataTest)

inputTrain = dataTrain[:, 0:5]
inputTest = dataTest[:, 0:5]
labelTrain = dataTrain[:, 5]
labelTest = dataTest[:, 5]
print(labelTrain)
len(labelTrain)

model = tree.DecisionTreeClassifier()

model = model.fit(inputTrain, labelTrain)

hasilPrediksi = model.predict(inputTest)
print("Label Sebenarnya : ", labelTest)
print("Hasil Prediksi : ", hasilPrediksi)

prediksiBenar = (hasilPrediksi == labelTest).sum()
prediksiSalah = (hasilPrediksi != labelTest).sum()
print("Prediksi Benar = ", prediksiBenar, "data")
print("Prediksi Salah = ", prediksiSalah, "data")
print("Akurasi = ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")
